<a href="https://colab.research.google.com/github/davidandw190/pytorch-deep-learning-workspace/blob/main/notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## 00. PyTorch Fundamentals

print('well, this is a start')


well, this is a start


In [2]:
!nvidia-smi

Thu Jun 27 15:38:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
import pandas as pd
import numpy
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Intro to Tensors

Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape `[3, 224, 224]` which would mean `[colour_channels, height, width]`, as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

### Creating tensors

**DOCS HERE**: [torch.Tensor](https://pytorch.org/docs/stable/tensors.html)


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()


7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# Dimension is kinda like, spatial representation. You can look at it as 'number of pairs of brackets' haha
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim


2

In [12]:
MATRIX.shape


torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random tensors

We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've being doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`



In [15]:
# Create random tensor of size/shape (3, 4)
rand_tensor = torch.rand(3, 4)

rand_tensor, rand_tensor.dtype

(tensor([[0.0784, 0.6164, 0.3071, 0.9985],
         [0.7957, 0.7002, 0.9725, 0.6265],
         [0.0474, 0.5385, 0.9713, 0.0998]]),
 torch.float32)

In [16]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones
Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with `torch.zeros()`

Again, the `size` parameter comes into play.

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

We can do the same to create a tensor of all ones except using `torch.ones()` instead.

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Create a tensor of all ones

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use `torch.arange(start, end, step)` to do so.

Where:

- start = start of range (e.g. 0)
- end = end of range (e.g. 10)
- step = how many steps in between each value (e.g. 1)

Note: In Python, you can use `range()` to create a range. However in PyTorch, `torch.range()` is deprecated and may show an error in the future.

In [19]:
# Use torch.arange(), torch.range() is deprecated
# zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensor Datatypes



In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,            # defaults to None, which is torch.float32 or whatever datatype is passed
                               device='cuda',           # defaults to None, which uses the default tensor type
                               requires_grad=False)   # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cuda', index=0))

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

! Three of the most common attributes you'll want to find out about tensors are:

- `shape` - what shape is the tensor? (some operations require specific shape rules)
- `dtype` - what datatype are the elements within the tensor stored in?
- `device` - what device is the tensor stored on? (usually GPU or CPU)

**Note**: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":

- *"what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"*

In [22]:
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3936, 0.2064, 0.5099, 0.7532],
        [0.7441, 0.4292, 0.0051, 0.3262],
        [0.7342, 0.4615, 0.8575, 0.3305]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [24]:
another_tensor = torch.rand(size=(5, 6),
                            dtype=torch.float64,
                            device='cuda')

print(another_tensor)
print(f"Shape of tensor: {another_tensor.shape}")
print(f"Datatype of tensor: {another_tensor.dtype}")
print(f"Device tensor is stored on: {another_tensor.device}")

tensor([[0.9738, 0.8777, 0.9005, 0.3231, 0.2227, 0.2590],
        [0.2011, 0.8207, 0.7084, 0.3853, 0.5185, 0.2993],
        [0.9855, 0.6353, 0.0260, 0.2786, 0.7746, 0.3573],
        [0.8185, 0.7880, 0.0061, 0.9582, 0.9974, 0.8056],
        [0.8989, 0.2252, 0.1083, 0.0373, 0.0374, 0.4559]], device='cuda:0',
       dtype=torch.float64)
Shape of tensor: torch.Size([5, 6])
Datatype of tensor: torch.float64
Device tensor is stored on: cuda:0
