<a href="https://colab.research.google.com/github/davidandw190/pytorch-deep-learning-workspace/blob/main/notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## 00. PyTorch Fundamentals

print('well, this is a start')


well, this is a start


In [2]:
!nvidia-smi

Sat Jun 29 13:14:53 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
import torch
import pandas as pd
import numpy
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Intro to Tensors

Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape `[3, 224, 224]` which would mean `[colour_channels, height, width]`, as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

### Creating tensors

**DOCS HERE**: [torch.Tensor](https://pytorch.org/docs/stable/tensors.html)


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()


7

In [7]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
# Dimension is kinda like, spatial representation. You can look at it as 'number of pairs of brackets' haha
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim


2

In [12]:
MATRIX.shape


torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

## Random tensors

We've established tensors represent some form of data.

And machine learning models such as neural networks manipulate and seek patterns within tensors.

But when building machine learning models with PyTorch, it's rare you'll create tensors by hand (like what we've being doing).

Instead, a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

In essence:

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`



In [15]:
# Create random tensor of size/shape (3, 4)
rand_tensor = torch.rand(3, 4)

rand_tensor, rand_tensor.dtype

(tensor([[0.8672, 0.8890, 0.7566, 0.2554],
         [0.9528, 0.1912, 0.1266, 0.3461],
         [0.1786, 0.2031, 0.8812, 0.6155]]),
 torch.float32)

In [16]:
# Create a random tensor of size (224, 224, 3)
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones
Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with masking (like masking some of the values in one tensor with zeros to let a model know not to learn them).

Let's create a tensor full of zeros with `torch.zeros()`

Again, the `size` parameter comes into play.

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

We can do the same to create a tensor of all ones except using `torch.ones()` instead.

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Create a tensor of all ones

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use `torch.arange(start, end, step)` to do so.

Where:

- start = start of range (e.g. 0)
- end = end of range (e.g. 10)
- step = how many steps in between each value (e.g. 1)

Note: In Python, you can use `range()` to create a range. However in PyTorch, `torch.range()` is deprecated and may show an error in the future.

In [19]:
# Use torch.arange(), torch.range() is deprecated
# zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensor Datatypes



In [20]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,            # defaults to None, which is torch.float32 or whatever datatype is passed
                               device='cuda',           # defaults to None, which uses the default tensor type
                               requires_grad=False)   # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cuda', index=0))

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

## Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

! Three of the most common attributes you'll want to find out about tensors are:

- `shape` - what shape is the tensor? (some operations require specific shape rules)
- `dtype` - what datatype are the elements within the tensor stored in?
- `device` - what device is the tensor stored on? (usually GPU or CPU)

**Note**: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":

- *"what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"*

In [22]:
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.3791, 0.8021, 0.8918, 0.1623],
        [0.1919, 0.2458, 0.8098, 0.8756],
        [0.7616, 0.0632, 0.0203, 0.7188]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [23]:
another_tensor = torch.rand(size=(5, 6),
                            dtype=torch.float64,
                            device='cuda')

print(another_tensor)
print(f"Shape of tensor: {another_tensor.shape}")
print(f"Datatype of tensor: {another_tensor.dtype}")
print(f"Device tensor is stored on: {another_tensor.device}")

tensor([[0.0121, 0.1767, 0.6846, 0.0835, 0.3954, 0.0356],
        [0.9858, 0.5617, 0.6927, 0.4396, 0.9994, 0.7910],
        [0.8632, 0.7701, 0.9883, 0.3134, 0.6461, 0.3687],
        [0.1827, 0.7447, 0.8733, 0.7239, 0.2615, 0.4682],
        [0.0795, 0.9720, 0.7534, 0.8064, 0.1139, 0.5881]], device='cuda:0',
       dtype=torch.float64)
Shape of tensor: torch.Size([5, 6])
Datatype of tensor: torch.float64
Device tensor is stored on: cuda:0


## Manipulating tensors (tensor operations)

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

- Addition
- Substraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

And that's it. Sure there are a few more here and there but these are the basic building blocks of neural networks.

Stacking these building blocks in the right way, you can create the most sophisticated of neural networks (just like lego!).


### Basic operations

In [24]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [25]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

Notice how the tensor values above didn't end up being `tensor([110, 120, 130])`, this is because the values inside the tensor don't change unless they're reassigned.

In [26]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [27]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [28]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])


PyTorch also has a bunch of built-in functions like `torch.mul()` (short for multiplication) and torch.add() to perform basic operations.

In [29]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [30]:
# Original tensor is still unchanged
tensor


tensor([1, 2, 3])

## Matrix multiplication (is all you need)

One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the `torch.matmul()` method.

The main two rules for matrix multiplication to remember are:

1. The inner dimensions must match:
  - `(3, 2) @ (3, 2)` won't work
  - `(2, 3) @ (3, 2)` will work
  - `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the outer dimensions:
  - `(2, 3) @ (3, 2)` -> `(2, 2)`
  - `(3, 2) @ (2, 3)` -> `(3, 3)`

Note: "@" in Python is the symbol for matrix multiplication.

In [31]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

## One of the most common errors: shape errors

Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [32]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

# torch.matmul(tensor_A, tensor_B) # (this will error)

We can make matrix multiplication work between `tensor_A` and `tensor_B` by making their inner dimensions match.

One of the ways to do this is with a *transpose* (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

- `torch.transpose(input, dim0, dim1)` - where input is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
- `tensor.T` - where tensor is the desired tensor to transpose.

In [33]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [34]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [35]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


Without the transpose, the rules of matrix mulitplication aren't fulfilled and we get an error like above.

## Tensor aggregation

A few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).


In [36]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


  **Note**: Some methods such as torch.mean() require tensors to be in torch.float32 (the most common) or another specific datatype, otherwise the operation will fail.


  You can also do the same as above with torch methods.
  

In [38]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)


(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional min/max

You can also find the index of a tensor where the max or minimum occurs with `torch.argmax()` and `torch.argmin()` respectively.

This is helpful in case you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).

In [39]:
# Create a tensor
tensor = torch.rand(size=(2, 4, 5))
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([[[0.7797, 0.9256, 0.7892, 0.8957, 0.0456],
         [0.7376, 0.6843, 0.0147, 0.2430, 0.6135],
         [0.7182, 0.3942, 0.0954, 0.4825, 0.5433],
         [0.8441, 0.2377, 0.0499, 0.3421, 0.6295]],

        [[0.6160, 0.6416, 0.5357, 0.5500, 0.1603],
         [0.2279, 0.8777, 0.8892, 0.5307, 0.0718],
         [0.5473, 0.7592, 0.3483, 0.7729, 0.4573],
         [0.5577, 0.8596, 0.2981, 0.7155, 0.8907]]])
Index where max value occurs: 1
Index where min value occurs: 7


## Change tensor datatype

As mentioned, a common issue with deep learning operations is having your tensors in different datatypes.

If one tensor is in `torch.float64` and another is in `torch.float32`, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using `torch.Tensor.type(dtype=None)` where the dtype parameter is the datatype you'd like to use.



In [40]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [41]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [42]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8


tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## Reshaping, stacking, squeezing and unsqueezing

- Reshaping - reshapes and input tensor to a defined shape
- View - return a  view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensors on top of each other (vstack) or side-by-side(hstack)
- Squeeze - removes all `1` dimensios from a tensor
- Unsqueeze - add a `1` dimension to a target tensor
- Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [43]:
import torch
x = torch.arange(1, 10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [44]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9, 1)
x_reshaped, x_reshaped.shape

(tensor([[[1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9]]]),
 torch.Size([1, 9, 1]))

In [45]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [46]:
# Changing z changes x, becauze a voew of a tensor shares the same memory  as the original
z[:, 0] = 5
z, x


(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [47]:
# Stack tensors on top of eachother
x_stacked = torch.stack([x, x, x, x], dim=0)
x, x_stacked

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9],
         [5, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [48]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x, x_stacked

(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([[5, 5, 5, 5],
         [2, 2, 2, 2],
         [3, 3, 3, 3],
         [4, 4, 4, 4],
         [5, 5, 5, 5],
         [6, 6, 6, 6],
         [7, 7, 7, 7],
         [8, 8, 8, 8],
         [9, 9, 9, 9]]))

In [50]:
# torch.squeeze() - removes al single dimensions from a target tensor
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [51]:
x_stacked.squeeze()

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [52]:
x_test = torch.zeros([1, 3, 4, 1, 2])
x_test, x_test.size

(tensor([[[[[0., 0.]],
 
           [[0., 0.]],
 
           [[0., 0.]],
 
           [[0., 0.]]],
 
 
          [[[0., 0.]],
 
           [[0., 0.]],
 
           [[0., 0.]],
 
           [[0., 0.]]],
 
 
          [[[0., 0.]],
 
           [[0., 0.]],
 
           [[0., 0.]],
 
           [[0., 0.]]]]]),
 <function Tensor.size>)

In [53]:
x_test.squeeze()


tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [54]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[[5],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]])
Previous shape: torch.Size([1, 9, 1])

New tensor: tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])
New shape: torch.Size([9])


In [58]:
x_og = torch.rand(size=(224, 224, 3)) # [height, width, color_channels]

# Permute the og tensor to rearrance the axis (or dim) order
x_permuted = x_og.permute(2, 0, 1)
print(f"Previous shape: {x_og.shape}")
x_og[0,0,0] = 123
print(f"New shape: {x_permuted.shape}")
x_permuted[0,0,0]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


tensor(123.)

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy



In [59]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
x[0, 0]

tensor([1, 2, 3])

In [62]:
x[0, 0, 2]

tensor(3)

In [63]:
x[0, 0, -1]

tensor(3)

In [64]:
x[0, 0, :]

tensor([1, 2, 3])

In [66]:
x[0, 0, :1]

tensor([1])