<a href="https://colab.research.google.com/github/davidandw190/pytorch-deep-learning-workspace/blob/main/notebooks/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
## 00. PyTorch Fundamentals

print('well, this is a start')


well, this is a start


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## Intro to Tensors

Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape `[3, 224, 224]` which would mean `[colour_channels, height, width]`, as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

### Creating tensors

**DOCS HERE**: [torch.Tensor](https://pytorch.org/docs/stable/tensors.html)


In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()


7

In [10]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
# Dimension is kinda like, spatial representation. You can look at it as 'number of pairs of brackets' haha
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [14]:
# MATRIX
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim


2

In [17]:
MATRIX.shape


torch.Size([2, 2])

In [20]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [21]:
TENSOR[0]


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])